### ISSUE TITLE
Need for more documentation

### ISSUE THREAD

**Issue by heniotierra** [codevibess/openssl-nodejs#1]
I was unable to find documentation on how to actually encrypt and decrypt data. I'm sorry if I missed it.

**Comment by codevibess** [comment]
Hi, 

Every manipulation with data you do by openssl, here you have documentation https://www.openssl.org/docs/.

openssl-nodejs package is the only wrapper to handle all operations in nodejs in a handy way.
If you have problems with function invocation, just tell and I will try to explein/add some more docs

King Regards,
Andrii
