### ISSUE TITLE
Error: spawn openssl ENOENT

### ISSUE THREAD

**Issue by ManGoatPig** [codevibess/openssl-nodejs#21]
I followed the directions in the readme for setting up.

1. `const openssl = require('openssl-nodejs');`
2.
```
openssl('openssl s_client -showcerts -verify 5 -connect RemovedMyDomainOnPurpose.com:443 < /dev/null', (data) => {
        console.log(data);
    });
```

This returns the following error,

Error: spawn openssl ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:478:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)

The certs are there and they work, I just want to get them.

Here is my OpenSSL version:
![image](https://user-images.githubusercontent.com/35311178/228007933-fb4ee751-d634-438d-b014-7087b3170302.png)

EDIT:
I also tried installing the below version of OpenSSL and received the same problem.
OpenSSL 1.1.1t  7 Feb 2023

**Comment by thavus** [comment]
I restarted my PC and it started working. Maybe PM2 just needed to reinizialize? Restarted pm2 servers didn't help before I restarted.

**Comment by ManGoatPig** [comment]
I restarted my PC and it started working. Maybe PM2 just needed to reinizialize? Restarting my pm2 servers didn't help before I restarted my PC.
